# Generated by Django 2.2.1 on 2019-06-17 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='type',
            field=models.CharField(default='Demo', max_length=40),
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iris', models.IntegerField(choices=[(0, 'Iris-setosa'), (1, 'Iris-versicolor'), (2, 'Iris-virginica')])),
                ('sepal_length', models.FloatField()),
                ('sepal_width', models.FloatField()),
                ('petal_length', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Load')),
            ],
        ),
    ]
