# Generated by Django 2.2.1 on 2019-06-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190617_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='iris',
            field=models.CharField(choices=[('Iris-setosa', 'Iris-setosa'), ('Iris-versicolor', 'Iris-versicolor'), ('Iris-virginica', 'Iris-virginica')], max_length=40),
        ),
    ]
