# Generated by Django 2.2.1 on 2019-06-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190617_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='text',
        ),
        migrations.AddField(
            model_name='load',
            name='file',
            field=models.FileField(default='empty', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
