# Generated by Django 2.2.1 on 2019-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190617_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
