# Generated by Django 2.2.1 on 2019-06-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190622_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='work_status',
            field=models.IntegerField(default=0),
        ),
    ]
