# Generated by Django 2.2.1 on 2019-06-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_person_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPriznak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Priznak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='payer_type',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.PayerType'),
        ),
        migrations.AddField(
            model_name='person',
            name='snils',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='suprug',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='_suprug', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='payer',
            name='payer_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.PayerType'),
        ),
        migrations.CreateModel(
            name='PersonPriznakLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
                ('priznak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Priznak')),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='fpriznak',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.FamilyPriznak'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='priznak',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.Priznak'),
        ),
    ]
