# Generated by Django 2.2.1 on 2019-06-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190622_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='for_whom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_for_whom', to='app.Person'),
        ),
    ]
