# Generated by Django 2.2.1 on 2019-06-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190622_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='child_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
