# Generated by Django 2.2.1 on 2019-06-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_answers_oprosnik_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='capital',
            name='start',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personpriznaklink',
            name='end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personpriznaklink',
            name='start',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('person', 'question')},
        ),
    ]
