# Generated by Django 2.2.1 on 2019-06-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190623_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personpriznaklink',
            name='start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
